### ISSUE TITLE
Add VIM support to base

### ISSUE THREAD

**Issue by jrhodes-sitback** [chinthakagodawita/docker-containers#16]

**Comment by chinthakagodawita** [comment]
Fixed in bfa24de0e0bb498d94c43f1f4448645bc0ff8ef8

**Comment by jrhodes-sitback** [comment]
:)

On Wed, Sep 16, 2015 at 10:36 AM, Chin Godawita <notifications@github.com>
wrote:

> Fixed in bfa24de
> <https://github.com/chinthakagodawita/docker-containers/commit/bfa24de0e0bb498d94c43f1f4448645bc0ff8ef8>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chinthakagodawita/docker-containers/issues/16#issuecomment-140587856>
> .
>



-- 
Jonathan Rhodes | Senior Drupal Developer

-- 
 39 - 41 Lower Fort Street, The Rocks, Sydney. 2000
<https://www.facebook.com/pages/Sitback/159057074134649>  
<https://twitter.com/Sitback>  
<http://www.linkedin.com/company/1482531?trk=tyah&trkInfo=tarId%3A1413439096225%2Ctas%3ASitback%2Cidx%3A2-1-4>
<http://www.sitback.com.au>

**Comment by chinthakagodawita** [comment]
Published in [build 115](https://circleci.com/gh/chinthakagodawita/docker-containers/115).
